/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DevRouteImport } from './routes/dev'
import { Route as DesignRouteImport } from './routes/design'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiBotHookRouteImport } from './routes/api/bot-hook'
import { Route as ApiStickerFilenameRouteImport } from './routes/api/sticker/$filename'
import { Route as ApiStickerGenerateQrcodeRouteImport } from './routes/api/sticker/generate/qrcode'
import { Route as ApiStickerGenerateCalendarRouteImport } from './routes/api/sticker/generate/calendar'

const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBotHookRoute = ApiBotHookRouteImport.update({
  id: '/api/bot-hook',
  path: '/api/bot-hook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStickerFilenameRoute = ApiStickerFilenameRouteImport.update({
  id: '/api/sticker/$filename',
  path: '/api/sticker/$filename',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStickerGenerateQrcodeRoute =
  ApiStickerGenerateQrcodeRouteImport.update({
    id: '/api/sticker/generate/qrcode',
    path: '/api/sticker/generate/qrcode',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiStickerGenerateCalendarRoute =
  ApiStickerGenerateCalendarRouteImport.update({
    id: '/api/sticker/generate/calendar',
    path: '/api/sticker/generate/calendar',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/dev': typeof DevRoute
  '/api/bot-hook': typeof ApiBotHookRoute
  '/api/sticker/$filename': typeof ApiStickerFilenameRoute
  '/api/sticker/generate/calendar': typeof ApiStickerGenerateCalendarRoute
  '/api/sticker/generate/qrcode': typeof ApiStickerGenerateQrcodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/dev': typeof DevRoute
  '/api/bot-hook': typeof ApiBotHookRoute
  '/api/sticker/$filename': typeof ApiStickerFilenameRoute
  '/api/sticker/generate/calendar': typeof ApiStickerGenerateCalendarRoute
  '/api/sticker/generate/qrcode': typeof ApiStickerGenerateQrcodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/dev': typeof DevRoute
  '/api/bot-hook': typeof ApiBotHookRoute
  '/api/sticker/$filename': typeof ApiStickerFilenameRoute
  '/api/sticker/generate/calendar': typeof ApiStickerGenerateCalendarRoute
  '/api/sticker/generate/qrcode': typeof ApiStickerGenerateQrcodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/design'
    | '/dev'
    | '/api/bot-hook'
    | '/api/sticker/$filename'
    | '/api/sticker/generate/calendar'
    | '/api/sticker/generate/qrcode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/design'
    | '/dev'
    | '/api/bot-hook'
    | '/api/sticker/$filename'
    | '/api/sticker/generate/calendar'
    | '/api/sticker/generate/qrcode'
  id:
    | '__root__'
    | '/'
    | '/design'
    | '/dev'
    | '/api/bot-hook'
    | '/api/sticker/$filename'
    | '/api/sticker/generate/calendar'
    | '/api/sticker/generate/qrcode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesignRoute: typeof DesignRoute
  DevRoute: typeof DevRoute
  ApiBotHookRoute: typeof ApiBotHookRoute
  ApiStickerFilenameRoute: typeof ApiStickerFilenameRoute
  ApiStickerGenerateCalendarRoute: typeof ApiStickerGenerateCalendarRoute
  ApiStickerGenerateQrcodeRoute: typeof ApiStickerGenerateQrcodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bot-hook': {
      id: '/api/bot-hook'
      path: '/api/bot-hook'
      fullPath: '/api/bot-hook'
      preLoaderRoute: typeof ApiBotHookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sticker/$filename': {
      id: '/api/sticker/$filename'
      path: '/api/sticker/$filename'
      fullPath: '/api/sticker/$filename'
      preLoaderRoute: typeof ApiStickerFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sticker/generate/qrcode': {
      id: '/api/sticker/generate/qrcode'
      path: '/api/sticker/generate/qrcode'
      fullPath: '/api/sticker/generate/qrcode'
      preLoaderRoute: typeof ApiStickerGenerateQrcodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sticker/generate/calendar': {
      id: '/api/sticker/generate/calendar'
      path: '/api/sticker/generate/calendar'
      fullPath: '/api/sticker/generate/calendar'
      preLoaderRoute: typeof ApiStickerGenerateCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesignRoute: DesignRoute,
  DevRoute: DevRoute,
  ApiBotHookRoute: ApiBotHookRoute,
  ApiStickerFilenameRoute: ApiStickerFilenameRoute,
  ApiStickerGenerateCalendarRoute: ApiStickerGenerateCalendarRoute,
  ApiStickerGenerateQrcodeRoute: ApiStickerGenerateQrcodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
